version: '3'
services:
  tf:
    build: .
    restart: always
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    ports:
      - 8888:8888
    volumes:
      - './notebooks:/tf/notebooks'